server:
  context-path: /springbootdemo1
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.108.106:3306/ems
    username: root
    password: 123456
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lj.entity

